# Generated by Django 4.0.5 on 2022-06-17 17:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phoneNumber', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField()),
                ('createdTs', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
